### PR TITLE
Bump Material-UI to beta.4

### PR DESCRIPTION
**Pull request by WatanabeToshimitsu**
## What?
- Bump Material-UI
- 最低限動くように useStyles を書き換えた

## Why?
- アップデートに追従したいので

## See also
- https://next.material-ui.com/guides/migration-v4/

### CODE REVIEW

**Comment by hdl-service** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/dataware-tools/app-common/pull/87#" title="Author self-approved">WatanabeToshimitsu</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=dataware-tools%2Fapp-common).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/dataware-tools/app-common/blob/master/OWNERS)~~ [WatanabeToshimitsu]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by WatanabeToshimitsu** [comment]
@d-hayashi 
[bump/material-ui ブランチの data-browser-next](https://github.com/dataware-tools/app-data-browser-next/pull/132) とStorybook が概ね今まで通り動くような，最低限の変更を行いました
コード自体はただ機械的にドキュメントに従っただけですので，あまり精査してもらわずとも大丈夫です
もしお時間ないなら，動作確認はこちらでもしているので，そのまま通してくださってもOKです

**Review by d-hayashi — APPROVED** [review]
LGTM

**Comment by hdl-service** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/dataware-tools/app-common/pull/87#pullrequestreview-736689946" title="Approved">d-hayashi</a>*, *<a href="https://github.com/dataware-tools/app-common/pull/87#" title="Author self-approved">WatanabeToshimitsu</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=dataware-tools%2Fapp-common).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/dataware-tools/app-common/blob/master/OWNERS)~~ [WatanabeToshimitsu,d-hayashi]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
